server:
  port: 8888
spring:
  application:
    name: springboot-data-jpa-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springboot_data_jpa?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true #真正开发中可能有延迟加载，需要将EntityManager延迟关闭
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8