server:
  port: 8888
spring:
  application:
    name: springboot-mybatis-demo
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springboot-mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bjlemon.springboot.domain
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
