server:
  port: 8888
  spring:
    application:
      name: springboot-web-demo
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - classpath:/demo/