server:
  port: 8080
spring:
  application:
    name: springboot-security-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springboot_security_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.bjlemon.springboot.domain
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true