server:
  port: 8080
spring:
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///departmentmanager?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: wdylzyn
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #      初始连接数
      initial-size: 5
      #      最大并发连接数
      max-active: 20
      #      最小空闲连接数
      min-idle: 5
      #      获取连接等待超时时间
      max-wait: 6000
mybatis:
  type-aliases-package: com.department.manager.domain
#  放在resource下单独指定，放在java中不加载
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    cache-enabled: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
#自动映射配置
#    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

